# Example lists of names traditionally associated with a particular gender
male_names = ['John', 'James', 'Robert', 'Michael', 'William', 'David', 'Richard', 'Joseph', 'Thomas', 'Charles', 'Christopher', 'Daniel', 'Matthew', 'Anthony', 'Mark', 'Donald', 'Steven', 'Paul', 'Andrew', 'Joshua', 'Kenneth', 'Kevin', 'Brian', 'George', 'Edward', 'Ronald', 'Timothy', 'Jason', 'Jeffrey', 'Ryan', 'Jacob', 'Gary', 'Nicholas', 'Eric', 'Jonathan', 'Stephen', 'Larry', 'Justin', 'Scott', 'Brandon', 'Benjamin', 'Samuel', 'Gregory', 'Frank', 'Alexander', 'Raymond', 'Patrick', 'Jack', 'Dennis', 'Jerry', 'Tyler', 'Aaron', 'Jose', 'Adam', 'Henry', 'Nathan', 'Douglas', 'Zachary', 'Peter', 'Kyle', 'Walter', 'Ethan', 'Jeremy', 'Harold', 'Keith', 'Christian', 'Roger', 'Noah', 'Gerald', 'Carl', 'Terry', 'Sean', 'Austin', 'Arthur', 'Lawrence', 'Jesse', 'Dylan', 'Bryan', 'Joe', 'Jordan', 'Billy', 'Bruce', 'Albert', 'Willie', 'Gabriel', 'Logan', 'Alan', 'Juan', 'Wayne', 'Roy', 'Ralph', 'Randy', 'Eugene', 'Vincent', 'Russell', 'Elijah', 'Louis', 'Bobby', 'Philip', 'Johnny']
female_names = ['Mary', 'Patricia', 'Jennifer', 'Linda', 'Elizabeth', 'Barbara', 'Susan', 'Jessica', 'Sarah', 'Karen', 'Nancy', 'Lisa', 'Betty', 'Margaret', 'Sandra', 'Ashley', 'Kimberly', 'Emily', 'Donna', 'Michelle', 'Dorothy', 'Carol', 'Amanda', 'Melissa', 'Deborah', 'Stephanie', 'Rebecca', 'Sharon', 'Laura', 'Cynthia', 'Kathleen', 'Amy', 'Shirley', 'Angela', 'Helen', 'Anna', 'Brenda', 'Pamela', 'Nicole', 'Emma', 'Samantha', 'Katherine', 'Christine', 'Debra', 'Rachel', 'Catherine', 'Carolyn', 'Janet', 'Ruth', 'Maria', 'Heather', 'Diane', 'Virginia', 'Julie', 'Joyce', 'Victoria', 'Olivia', 'Kelly', 'Christina', 'Lauren', 'Joan', 'Evelyn', 'Judith', 'Megan', 'Cheryl', 'Andrea', 'Hannah', 'Martha', 'Jacqueline', 'Frances', 'Gloria', 'Ann', 'Teresa', 'Kathryn', 'Sara', 'Janice', 'Marie', 'Julia', 'Grace', 'Judy', 'Theresa', 'Madison', 'Beverly', 'Denise', 'Marilyn', 'Amber', 'Danielle', 'Rose', 'Brittany', 'Diana', 'Abigail', 'Natalie', 'Jane', 'Lori', 'Alexis', 'Tiffany', 'Kayla', 'Tammy', 'Crystal', 'Madison']
last_names = ['Smith', 'Johnson', 'Williams', 'Jones', 'Brown', 'Davis', 'Miller', 'Wilson', 'Moore', 'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson', 'Garcia', 'Martinez', 'Robinson', 'Clark', 'Rodriguez', 'Lewis', 'Lee', 'Walker', 'Hall', 'Allen', 'Young', 'Hernandez', 'King', 'Wright', 'Lopez', 'Hill', 'Scott', 'Green', 'Adams', 'Baker', 'Gonzalez', 'Nelson', 'Carter', 'Mitchell', 'Perez', 'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins', 'Stewart', 'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey', 'Rivera', 'Cooper', 'Richardson', 'Cox', 'Howard', 'Ward', 'Torres', 'Peterson', 'Gray', 'Ramirez', 'James', 'Watson', 'Brooks', 'Kelly', 'Sanders', 'Price', 'Bennett', 'Wood', 'Barnes', 'Ross', 'Henderson', 'Coleman', 'Jenkins', 'Perry', 'Powell', 'Long', 'Patterson', 'Hughes', 'Flores', 'Washington', 'Butler', 'Simmons', 'Foster', 'Gonzales', 'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz', 'Hayes']

# Example list of industries
businesses = ['Restaurant', 'Cafe', 'Bakery', 'Clothing Store', 'Shoe Store', 'Bookstore', 'Electronics Store', 'Hardware Store', 'Grocery Store', 'Convenience Store', 'Pharmacy', 'Florist', 'Jewellery Store', 'Pet Store', 'Toy Store', 'Furniture Store', 'Home Decor Store', 'Sporting Goods Store', 'Music Store', 'Movie Rental Store', 'Gift Shop', 'Art Gallery', 'Antique Shop', 'Thrift Store', 'Pawn Shop', 'Car Dealership', 'Auto Repair Shop', 'Gas Station', 'Car Wash', 'Bicycle Shop', 'Motorcycle Dealership', 'Tattoo Parlor', 'Hair Salon', 'Nail Salon', 'Beauty Supply Store', 'Spa', 'Gym', 'Yoga Studio', 'Dance Studio', 'Martial Arts School', 'Tutoring Center', 'Language School', 'Driving School', 'Music School', 'Art School', 'Daycare Center', 'Pet Grooming', 'Veterinary Clinic', 'Animal Shelter', 'Landscaping Service', 'Gardening Service', 'Cleaning Service', 'Plumbing Service', 'Electrician Service', 'Roofing Service', 'Construction Company', 'Painting Service', 'Carpentry Service', 'Moving Company', 'Storage Facility', 'Laundromat', 'Dry Cleaner', 'Alteration Service', 'Shoe Repair Service', 'Locksmith', 'Security Company', 'Insurance Agency', 'Real Estate Agency', 'Travel Agency', 'Event Planning Service', 'Catering Service', 'Food Truck', 'Ice Cream Shop', 'Smoothie Bar', 'Juice Bar', 'Coffee Shop', 'Tea House', 'Bar', 'Night Club', 'Comedy Club', 'Movie Theater', 'Bowling Alley', 'Arcade', 'Escape Room', 'Virtual Reality Arcade', 'Trampoline Park', 'Laser Tag Arena', 'Go-Kart Track', 'Mini Golf Course', 'Batting Cages', 'Parking Garage', 'Car Rental Agency', 'Taxi Service', 'Limousine Service', 'Photography Studio', 'Video Production Company', 'Web Design Agency', 'Marketing Agency', 'Public Relations Firm', 'Accounting Firm', 'Law Firm']

# Example list of problems
problems = ['billing', 'shipping', 'returns', 'customer service', 'product quality', 'inventory',
            'pricing', 'security', 'privacy', 'data management']

# Example list of emotions
emotions = ['happy', 'sad', 'angry', 'frustrated', 'confused', 'excited', 'nervous', 'relieved', 'surprised', 'disappointed']

