# Example lists of names traditionally associated with a particular gender
male_names = ['John', 'James', 'Robert', 'Michael', 'William', 'David', 'Richard', 'Joseph', 'Thomas', 'Charles', 'Christopher', 'Daniel', 'Matthew', 'Anthony', 'Mark', 'Donald', 'Steven', 'Paul', 'Andrew', 'Joshua', 'Kenneth', 'Kevin', 'Brian', 'George', 'Edward', 'Ronald', 'Timothy', 'Jason', 'Jeffrey', 'Ryan', 'Jacob', 'Gary', 'Nicholas', 'Eric', 'Jonathan', 'Stephen', 'Larry', 'Justin', 'Scott', 'Brandon', 'Benjamin', 'Samuel', 'Gregory', 'Frank', 'Alexander', 'Raymond', 'Patrick', 'Jack', 'Dennis', 'Jerry', 'Tyler', 'Aaron', 'Jose', 'Adam', 'Henry', 'Nathan', 'Douglas', 'Zachary', 'Peter', 'Kyle', 'Walter', 'Ethan', 'Jeremy', 'Harold', 'Keith', 'Christian', 'Roger', 'Noah', 'Gerald', 'Carl', 'Terry', 'Sean', 'Austin', 'Arthur', 'Lawrence', 'Jesse', 'Dylan', 'Bryan', 'Joe', 'Jordan', 'Billy', 'Bruce', 'Albert', 'Willie', 'Gabriel', 'Logan', 'Alan', 'Juan', 'Wayne', 'Roy', 'Ralph', 'Randy', 'Eugene', 'Vincent', 'Russell', 'Elijah', 'Louis', 'Bobby', 'Philip', 'Johnny']
female_names = ['Mary', 'Patricia', 'Jennifer', 'Linda', 'Elizabeth', 'Barbara', 'Susan', 'Jessica', 'Sarah', 'Karen', 'Nancy', 'Lisa', 'Betty', 'Margaret', 'Sandra', 'Ashley', 'Kimberly', 'Emily', 'Donna', 'Michelle', 'Dorothy', 'Carol', 'Amanda', 'Melissa', 'Deborah', 'Stephanie', 'Rebecca', 'Sharon', 'Laura', 'Cynthia', 'Kathleen', 'Amy', 'Shirley', 'Angela', 'Helen', 'Anna', 'Brenda', 'Pamela', 'Nicole', 'Emma', 'Samantha', 'Katherine', 'Christine', 'Debra', 'Rachel', 'Catherine', 'Carolyn', 'Janet', 'Ruth', 'Maria', 'Heather', 'Diane', 'Virginia', 'Julie', 'Joyce', 'Victoria', 'Olivia', 'Kelly', 'Christina', 'Lauren', 'Joan', 'Evelyn', 'Judith', 'Megan', 'Cheryl', 'Andrea', 'Hannah', 'Martha', 'Jacqueline', 'Frances', 'Gloria', 'Ann', 'Teresa', 'Kathryn', 'Sara', 'Janice', 'Marie', 'Julia', 'Grace', 'Judy', 'Theresa', 'Madison', 'Beverly', 'Denise', 'Marilyn', 'Amber', 'Danielle', 'Rose', 'Brittany', 'Diana', 'Abigail', 'Natalie', 'Jane', 'Lori', 'Alexis', 'Tiffany', 'Kayla', 'Tammy', 'Crystal', 'Madison']
last_names = ['Smith', 'Johnson', 'Williams', 'Jones', 'Brown', 'Davis', 'Miller', 'Wilson', 'Moore', 'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson', 'Garcia', 'Martinez', 'Robinson', 'Clark', 'Rodriguez', 'Lewis', 'Lee', 'Walker', 'Hall', 'Allen', 'Young', 'Hernandez', 'King', 'Wright', 'Lopez', 'Hill', 'Scott', 'Green', 'Adams', 'Baker', 'Gonzalez', 'Nelson', 'Carter', 'Mitchell', 'Perez', 'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins', 'Stewart', 'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey', 'Rivera', 'Cooper', 'Richardson', 'Cox', 'Howard', 'Ward', 'Torres', 'Peterson', 'Gray', 'Ramirez', 'James', 'Watson', 'Brooks', 'Kelly', 'Sanders', 'Price', 'Bennett', 'Wood', 'Barnes', 'Ross', 'Henderson', 'Coleman', 'Jenkins', 'Perry', 'Powell', 'Long', 'Patterson', 'Hughes', 'Flores', 'Washington', 'Butler', 'Simmons', 'Foster', 'Gonzales', 'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz', 'Hayes']

# Example list of industries
businesses = [
    'Pick Random Business Type',
    'Accounting Firm', 
    'Alteration Service', 
    'Animal Shelter', 
    'Antique Shop', 
    'Arcade', 
    'Art Gallery', 
    'Art School', 
    'Auto Repair Shop', 
    'Bakery', 
    'Bar', 
    'Batting Cages', 
    'Beauty Supply Store', 
    'Bicycle Shop', 
    'Bookstore', 
    'Bowling Alley', 
    'Cafe', 
    'Car Dealership', 
    'Car Rental Agency', 
    'Car Wash', 
    'Carpentry Service', 
    'Catering Service', 
    'Cleaning Service', 
    'Clothing Store', 
    'Coffee Shop', 
    'Comedy Club', 
    'Construction Company', 
    'Convenience Store', 
    'Dance Studio', 
    'Daycare Center', 
    'Driving School', 
    'Dry Cleaner', 
    'Electrician Service', 
    'Electronics Store', 
    'Escape Room', 
    'Event Planning Service', 
    'Florist', 
    'Food Truck', 
    'Furniture Store', 
    'Gardening Service', 
    'Gas Station', 
    'Gift Shop', 
    'Go-Kart Track', 
    'Grocery Store', 
    'Gym', 
    'Hair Salon', 
    'Hardware Store', 
    'Home Decor Store', 
    'Ice Cream Shop', 
    'Insurance Agency', 
    'Jewellery Store', 
    'Juice Bar', 
    'Landscaping Service', 
    'Language School', 
    'Laser Tag Arena', 
    'Laundromat', 
    'Law Firm',
    'Limousine Service', 
    'Locksmith', 
    'Marketing Agency', 
    'Martial Arts School', 
    'Mini Golf Course', 
    'Motorcycle Dealership', 
    'Movie Rental Store', 
    'Movie Theater', 
    'Moving Company', 
    'Music School', 
    'Music Store', 
    'Nail Salon', 
    'Night Club', 
    'Painting Service', 
    'Parking Garage', 
    'Pawn Shop', 
    'Pet Grooming', 
    'Pet Store', 
    'Pharmacy', 
    'Photography Studio', 
    'Plumbing Service', 
    'Public Relations Firm', 
    'Real Estate Agency', 
    'Restaurant', 
    'Roofing Service', 
    'Security Company', 
    'Shoe Repair Service', 
    'Shoe Store', 
    'Smoothie Bar', 
    'Spa', 
    'Sporting Goods Store', 
    'Storage Facility', 
    'Tattoo Parlor', 
    'Taxi Service', 
    'Tea House', 
    'Thrift Store', 
    'Toy Store', 
    'Trampoline Park', 
    'Travel Agency', 
    'Tutoring Center', 
    'Veterinary Clinic', 
    'Video Production Company', 
    'Virtual Reality Arcade', 
    'Web Design Agency', 
    'Yoga Studio'
    ]

# Example list of problems
problems = ['typical situation', 
            'random situation',
            'billing', 
            'shipping', 
            'returns', 
            'customer service', 
            'product quality', 
            'inventory',
            'pricing', 
            'security', 
            'privacy', 
            'data management']

# Example list of emotions
emotions = ['happy', 'sad', 'angry', 'frustrated', 'confused', 'excited', 'nervous', 'relieved', 'surprised', 'disappointed', 'relaxed', 'anxious']

